version: '2'

services:
  db:
    build: db/.
    volumes:
      - db:/var/lib/mysql/
  app:
    build: app/.
  web:
    build: web/.
    ports:
      - "127.0.0.1:8888:80"
volumes:
  db:
    driver: local
